### ISSUE TITLE
Where do I put the downloaded llava model?

### ISSUE THREAD

**Issue by msandroid** [denfrost/Den_ComfyUI_Workflow#1]
GPT および LLM モデルの使用: Llava、GGUF
https://huggingface.co/models?library=gguf&sort=trending&search=llava

**Comment by denfrost** [comment]
ComfyUI\models\LLM_checkpoints\

**Comment by denfrost** [comment]
can put models to here
ComfyUI\models\GPTcheckpoints\llava
have 2 folders for Clip and Model gguf
ComfyUI\models\GPTcheckpoints\llava\clips
ComfyUI\models\GPTcheckpoints\llava\models

updated readme thx
